version: '3.9'

services:
  app:
    image: c4illin/convertx:latest
    container_name: '{{APP_ID}}'
    restart: unless-stopped
    ports:
      - '{{APP_PORT}}:8080'
    volumes:
      - '{{APP_DATA_DIR}}/config:/config'
      - '{{APP_DATA_DIR}}/downloads:/downloads'
      - '{{APP_DATA_DIR}}/uploads:/uploads'